name: Build and Release Proxy Checker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 缓存 Go 模块
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 安装依赖
      - name: Install dependencies
        run: go mod download

      # 确保 builds-linux.sh 可执行并运行
      - name: Run builds-linux.sh
        run: |
          chmod +x ./builds-linux.sh
          ./builds-linux.sh aigo.go "${{ github.event.inputs.version || github.ref_name }}"

      # 检查 builds 目录是否存在
      - name: Verify build output
        run: |
          if [ ! -d "builds" ] || [ -z "$(ls -A builds)" ]; then
            echo "Error: No build artifacts found in builds/ directory"
            exit 1
          fi

      # 创建 GitHub Release 并上传资产
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Proxy Checker ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          restore-keys: |
            ${{ runner.os }}-go-

      # 安装依赖
      - name: Install dependencies
        run: go mod download

      # 确保 builds-linux.sh 可执行并运行
      - name: Run builds-linux.sh
        run: |
          chmod +x ./builds-linux.sh
          ./builds-linux.sh aigo.go "${{ github.event.inputs.version || github.ref_name }}"

      # 检查 builds 目录是否存在
      - name: Verify build output
        run: |
          if [ ! -d "builds" ] || [ -z "$(ls -A builds)" ]; then
            echo "Error: No build artifacts found in builds/ directory"
            exit 1
          fi

      # 创建 GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          release_name: Proxy Checker ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false

      # 上传所有二进制文件作为 Release 资产
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in builds/*; do
            if [ -f "$asset" ]; then
              asset_name=$(basename "$asset")
              echo "Uploading $asset_name..."
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/octet-stream" \
                --data-binary "@$asset" \
                "${{ steps.create_release.outputs.upload_url }}?name=$asset_name"
            else
              echo "Skipping $asset (not a file)"
            fi
          done
